name: Release Notes Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: release-notes-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest

    # ⬇️ AÑADIDO: secretos para AWS y Bedrock disponibles en todos los steps del job
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}   # quita esta línea si no usas credenciales temporales
      BEDROCK_MODEL_ID: ${{ secrets.BEDROCK_MODEL_ID }}

    steps:
      - name: Checkout PR repo (this repo)
        uses: actions/checkout@v4

      - name: Checkout agent repo
        uses: actions/checkout@v4
        with:
          repository: oscarcurtog/release-note-agent
          ref: main
          path: agent
          # token: ${{ secrets.AGENT_REPO_TOKEN }}  # solo si el agente es privado

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore cache (agent/.cache)
        uses: actions/cache@v4
        with:
          path: agent/.cache/release_notes
          key: release-notes-${{ github.event.pull_request.number }}-${{ github.sha }}
          restore-keys: |
            release-notes-${{ github.event.pull_request.number }}-

      - name: Install deps from agent repo
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt

      - name: Generate preview comment
        # ⬇️ GITHUB_TOKEN lo pasamos aquí (lo provee GitHub automáticamente)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: agent
        run: |
          python -m agents.release_notes_agent generate \
            --owner "${{ github.event.pull_request.base.repo.owner.login }}" \
            --repo  "${{ github.event.pull_request.base.repo.name }}" \
            --pr    ${{ github.event.pull_request.number }} \
            --single-chunk --preview
